from pathlib import Path
import argparse as arg
import inspect
import os
import pickle

import lightning as L
import torch

from sot_mol.comparm import GP, Update_PARAMS
from sot_mol.models.rl_interface import MolGen_RLModel


CELECOXIB_SMILES = "CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F"
PERINDOPRIL_SMILES = "CCC[C@@H](C(=O)OCC)N[C@@H](C)C(=O)N1[C@H]2CCCC[C@H]2C[C@H]1C(=O)O"


def _filter_smol_by_atom_count(src_path, min_atoms=None, max_atoms=None, out_dir=None, with_hs=True):
    """Create a temporary .smol file containing only molecules within an atom-count range.

    This controls the noise-template/mask/natoms distribution used by MGDataModule
    without modifying the datamodule or the original datasets. The serialized MolGraph
    bytes are kept unchanged; only the list of template molecules is filtered.
    """
    if min_atoms is None and max_atoms is None:
        return Path(src_path)

    from sot_mol.data.molgraph import MolGraph
    from rdkit import Chem

    src_path = Path(src_path)
    out_dir = Path(out_dir or src_path.parent)
    out_dir.mkdir(parents=True, exist_ok=True)

    min_tag = "min" if min_atoms is None else str(int(min_atoms))
    max_tag = "max" if max_atoms is None else str(int(max_atoms))
    out_path = out_dir / f"{src_path.stem}_atoms_{min_tag}_{max_tag}_pid{os.getpid()}.smol"

    datas = pickle.loads(src_path.read_bytes())
    kept = []
    failed = 0
    for data in datas:
        try:
            mg = MolGraph.from_bytes(data)
            mol = mg.to_rdkit()
            if mol is None:
                failed += 1
                continue
            if not with_hs:
                mol = Chem.RemoveHs(mol)
            n_atoms = int(mol.GetNumAtoms())
            if (min_atoms is None or n_atoms >= int(min_atoms)) and (max_atoms is None or n_atoms <= int(max_atoms)):
                kept.append(data)
        except Exception:
            failed += 1

    if len(kept) == 0:
        raise RuntimeError(
            f"Atom-count filtering produced 0 molecules for {src_path} with "
            f"min_atoms={min_atoms}, max_atoms={max_atoms}, with_hs={with_hs}. "
            f"Failed conversions: {failed}."
        )

    out_path.write_bytes(pickle.dumps(kept, protocol=pickle.HIGHEST_PROTOCOL))
    print(
        f"[atom-count filter] {src_path.name}: kept {len(kept)}/{len(datas)} molecules "
        f"with atoms in [{min_atoms}, {max_atoms}] (with_hs={with_hs}); failed={failed}; "
        f"output={out_path}"
    )
    return out_path


def _find_existing_filtered_smol(filtered_dir, split, min_atoms=None, max_atoms=None):
    """Return the most recently modified filtered .smol for a split/range.

    Expected names are generated by _filter_smol_by_atom_count, e.g.
        train_atoms_53_63_pid211425.smol
        val_atoms_53_63_pid118070.smol
        test_atoms_53_63_pid211070.smol
    """
    filtered_dir = Path(filtered_dir)
    min_tag = "min" if min_atoms is None else str(int(min_atoms))
    max_tag = "max" if max_atoms is None else str(int(max_atoms))
    pattern = f"{split}_atoms_{min_tag}_{max_tag}_pid*.smol"
    matches = sorted(filtered_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if not matches:
        raise FileNotFoundError(
            f"No existing filtered .smol found under {filtered_dir} with pattern {pattern}. "
            "Either pass --filtered_{split}_datafile explicitly, disable --use_existing_filtered_smol, "
            "or generate the filtered file once."
        )
    return matches[0]


def _resolve_datafile_for_split(
    split,
    default_path,
    args,
    should_filter_split,
):
    """Resolve which .smol file to use for train/val/test.

    Priority:
      1. Explicit --filtered_<split>_datafile path.
      2. Existing filtered_smol/<split>_atoms_<min>_<max>_pid*.smol when
         --use_existing_filtered_smol is enabled.
      3. Generate a new filtered file if atom-count filtering is requested.
      4. Original datasets/<split>.smol.
    """
    explicit = getattr(args, f"filtered_{split}_datafile", "")
    if explicit:
        p = Path(explicit)
        if not p.is_absolute():
            p = Path(args.script_dir_for_paths) / p
        if not p.exists():
            raise FileNotFoundError(f"Explicit filtered {split} datafile does not exist: {p}")
        print(f"[smol resolve] using explicit filtered {split}_datafile={p}")
        return p

    if not should_filter_split:
        return Path(default_path)

    filtered_dir = Path(args.filtered_smol_dir)
    if not filtered_dir.is_absolute():
        filtered_dir = Path(args.script_dir_for_paths) / filtered_dir

    if args.use_existing_filtered_smol:
        p = _find_existing_filtered_smol(
            filtered_dir,
            split=split,
            min_atoms=args.template_atom_count_min,
            max_atoms=args.template_atom_count_max,
        )
        print(f"[smol resolve] using existing filtered {split} file: {p}")
        return p

    return _filter_smol_by_atom_count(
        default_path,
        min_atoms=args.template_atom_count_min,
        max_atoms=args.template_atom_count_max,
        out_dir=filtered_dir,
        with_hs=bool(args.template_count_with_hs),
    )


def build_objective_config(args):
    """Build objective_config for the unified objective system in mpo_tasks.py.

    The actual reward is computed inside RL_Lightning via
    build_objective(objective_name, objective_config).score_mols(...).score.
    This function only supplies task-specific configuration and keeps non-MPO
    tasks from inheriting Ranolazine-specific settings.
    """
    obj_lower = args.objective_name.lower()

    if obj_lower == "qed":
        return {
            "aggregate": "geometric",
        }

    if obj_lower in ["celecoxib_similarity", "celecoxib_sim", "celecoxib_scaffold_hopping"]:
        return {
            "target_name": "celecoxib",
            "target_smiles": args.target_smiles or CELECOXIB_SMILES,
            "fp_type": args.similarity_fp,
            "radius": int(args.similarity_radius),
            "n_bits": int(args.similarity_n_bits),
            "similarity_threshold": args.similarity_threshold,
            "similarity_key": "sim_celecoxib",
            "feasibility": {"valid": True, "connected": True},
            # Extension hook: later promote QED/TPSA/logP from raw_properties into
            # component_scores/objective score inside TargetSimilarityObjective.
            "future_property_components": ["QED", "TPSA", "logP"],
        }

    if obj_lower in ["perindopril_similarity_aromatic", "perindopril_aromatic", "perindopril_scaffold_hopping"]:
        return {
            "target_smiles": args.target_smiles or PERINDOPRIL_SMILES,
            "fp_type": args.similarity_fp,
            "radius": int(args.similarity_radius),
            "n_bits": int(args.similarity_n_bits),
            "similarity_threshold": args.similarity_threshold,
            "similarity_key": "sim_perindopril",
            "aromatic_key": "aromatic_ring_reward",
            "raw_aromatic_key": "num_aromatic_rings",
            "target_aromatic_rings": 2,
            "near_aromatic_rings": [1, 3],
            "near_aromatic_score": float(args.perindopril_near_aromatic_score),
            "similarity_weight": float(args.perindopril_similarity_weight),
            "aromatic_weight": float(args.perindopril_aromatic_weight),
            "pareto_component_names": ["sim_perindopril", "aromatic_ring_reward"],
            "feasibility": {"valid": True, "connected": True},
        }

    if obj_lower in ["xtb", "xtb_force", "xtb_stability", "gfn2_xtb", "gfn2_xtb_force", "xtb_force_rms"]:
        return {
            "xtb_method": args.xtb_method,
            "force_norm": args.xtb_force_norm,
            "fail_penalty": float(args.xtb_fail_penalty),
            "fail_score": float(args.xtb_fail_score),
            "max_workers": int(args.xtb_max_workers),
            "timeout": args.xtb_timeout,
            "reward_scale": float(args.xtb_reward_scale),
            "reward_transform": args.xtb_reward_transform,
            "force_scale": float(args.xtb_force_scale),
            "linear_cutoff": float(args.xtb_linear_cutoff),
            "score_key": "xtb_reward",
            "pareto_component_names": ["xtb_reward"],
            "require_connected": True,
            "require_xtb_success_for_feasible": not bool(args.xtb_allow_failed_as_feasible),
            "feasibility": {"valid": True, "connected": True, "xtb_success": True},
        }

    if obj_lower in ["psa_min", "psa3d_min"]:
        return {
            "psa_center": float(args.psa_center),
            "psa_k": float(args.psa_k),
            "psa_add_hs": bool(args.psa_add_hs),
            "psa_include_polar_hs": bool(args.psa_include_polar_hs),
        }

    if obj_lower in ["qed_sa", "qed_sa_min", "qedsa", "qed_sa_mpo"]:
        return {
            "aggregate": "geometric",
            "sa_transform": args.sa_transform,
            "component_weights": {
                "qed": float(args.qed_weight),
                "SA": float(args.sa_weight),
            },
            "pareto_component_names": ["qed", "SA"],
            "sa_allow_proxy": bool(args.sa_allow_proxy),
            "feasibility": {"valid": True, "connected": True},
        }

    # Fallback for existing MPO tasks such as Ranolazine_MPO / Osimertinib_MPO.
    return {
        "aggregate": args.aggregate,
        "use_official_guacamol": bool(args.use_official_guacamol),
        "fallback_aggregate": "geometric",
        "pareto_component_names": ["sim_ranolazine_AP", "logP", "TPSA", "num_F"],
        "feasibility": {"valid": True, "connected": True},
    }


parser = arg.ArgumentParser(description="Reward-Weighted FM RL training with unified objectives")
parser.add_argument("--config", type=str, default="rl.json")
parser.add_argument("--objective_name", type=str, default="qed",
                    help="Objective registered in sot_mol.rl_objectives.mpo_tasks, e.g. qed, PSA_Min, QED_SA")
parser.add_argument("--project_name", type=str, default="",
                    help="TensorBoard/checkpoint project name. Defaults to SOTMOL_RL_<objective>.")
parser.add_argument("--target_smiles", type=str, default="",
                    help="Reference SMILES for target_similarity / celecoxib_similarity objectives.")
parser.add_argument("--similarity_fp", type=str, default="morgan", choices=["morgan", "ecfp", "ecfp4", "ap", "atom_pair", "rdkit"],
                    help="Fingerprint used for Tanimoto similarity.")
parser.add_argument("--similarity_radius", type=int, default=2,
                    help="Morgan/ECFP radius. radius=2 corresponds to ECFP4.")
parser.add_argument("--similarity_n_bits", type=int, default=2048)
parser.add_argument("--similarity_threshold", type=float, default=None,
                    help="Optional capped reward min(sim, threshold)/threshold. Leave unset for raw Tanimoto.")
parser.add_argument("--perindopril_similarity_weight", type=float, default=0.8,
                    help="Weight of Perindopril Tanimoto component in final reward.")
parser.add_argument("--perindopril_aromatic_weight", type=float, default=0.2,
                    help="Weight of aromatic-ring-count component in final reward.")
parser.add_argument("--perindopril_near_aromatic_score", type=float, default=0.5,
                    help="Aromatic component score when aromatic ring count is 1 or 3.")
parser.add_argument("--xtb_method", type=str, default="GFN2-xTB",
                    help="xTB method used by xtb.ase.calculator.XTB, e.g. GFN2-xTB.")
parser.add_argument("--xtb_force_norm", type=str, default="atom_rms", choices=["atom_rms", "component_rms"],
                    help="atom_rms = sqrt(mean_i ||F_i||^2); component_rms = sqrt(mean over xyz components).")
parser.add_argument("--xtb_reward_transform", type=str, default="bounded_inverse",
                    choices=["bounded_inverse", "bounded_exp", "linear_cutoff", "neg_force"],
                    help="How to transform xTB force RMS into reward. Default returns a 0-1 score where larger is better.")
parser.add_argument("--xtb_force_scale", type=float, default=1.0,
                    help="Scale for bounded_inverse/bounded_exp reward transforms. score=1/(1+force/scale) by default.")
parser.add_argument("--xtb_linear_cutoff", type=float, default=1.0,
                    help="Cutoff for linear_cutoff transform: score=clamp(1-force/cutoff,0,1).")
parser.add_argument("--xtb_fail_score", type=float, default=0.0,
                    help="0-1 score assigned when xTB fails or the molecule has no conformer.")
parser.add_argument("--xtb_fail_penalty", type=float, default=-5.0,
                    help="Penalty used only when --xtb_reward_transform neg_force, and for legacy worker failure bookkeeping.")
parser.add_argument("--xtb_max_workers", type=int, default=1,
                    help="Number of process workers for xTB reward calculation per rank. Start with 1 or 2.")
parser.add_argument("--xtb_timeout", type=float, default=120.0,
                    help="Per-molecule hard xTB timeout in seconds; <=0 disables timeout.")
parser.add_argument("--xtb_reward_scale", type=float, default=1.0,
                    help="Scale used only for neg_force transform: score=-reward_scale*force_rms.")
parser.add_argument("--xtb_allow_failed_as_feasible", action="store_true",
                    help="If set, failed xTB jobs are not excluded from feasible top selection, but still receive fail_penalty.")
parser.add_argument("--template_atom_count_min", type=int, default=None,
                    help="Optional minimum atom count for noise-template molecules. For Perindopril with explicit Hs, use 53.")
parser.add_argument("--template_atom_count_max", type=int, default=None,
                    help="Optional maximum atom count for noise-template molecules. For Perindopril with explicit Hs, use 63.")
parser.add_argument("--template_atom_count_splits", type=str, default="none", choices=["none", "train", "all"],
                    help="Which .smol splits to filter by atom count before creating the datamodule.")
parser.add_argument("--template_count_with_hs", action=arg.BooleanOptionalAction, default=True,
                    help="Count atoms with explicit hydrogens when filtering templates. Keep True if smol files were loaded with Hs.")
parser.add_argument("--filtered_train_datafile", type=str, default="",
                    help="Optional pre-filtered train .smol. Overrides automatic filtering and existing-file lookup.")
parser.add_argument("--filtered_val_datafile", type=str, default="",
                    help="Optional pre-filtered val .smol. Overrides automatic filtering and existing-file lookup.")
parser.add_argument("--filtered_test_datafile", type=str, default="",
                    help="Optional pre-filtered test .smol. Overrides automatic filtering and existing-file lookup.")
parser.add_argument("--filtered_smol_dir", type=str, default="filtered_smol",
                    help="Directory containing pre-filtered .smol files or where new filtered files are written.")
parser.add_argument("--use_existing_filtered_smol", action=arg.BooleanOptionalAction, default=False,
                    help="Use the newest existing filtered_smol/<split>_atoms_<min>_<max>_pid*.smol instead of regenerating it.")
parser.add_argument("--epochs", type=int, default=5)
parser.add_argument("--batchsize", type=int, default=48)
parser.add_argument("--mini_batchsize", type=int, default=1)
parser.add_argument("--max_steps", type=int, default=128)
parser.add_argument("--log_steps", type=int, default=1)
parser.add_argument("--seed", type=int, default=12345)
parser.add_argument("--regularization_type", type=str, default="Parametric_L2", choices=["KL", "Parametric_L2"])
parser.add_argument("--exp_tag", type=str, default="")

# RWR reward-to-weight settings.
parser.add_argument("--reward_beta", type=float, default=2.0)
parser.add_argument("--reward_weight_min", type=float, default=0.1)
parser.add_argument("--reward_weight_max", type=float, default=10.0)
parser.add_argument("--anchor_weight", type=float, default=0.1)
parser.add_argument("--anchor_loss_weight", type=float, default=1.0)
parser.add_argument("--disable_reference_anchor", action="store_true")

# PSA_Min settings.
parser.add_argument("--psa_center", type=float, default=75.0)
parser.add_argument("--psa_k", type=float, default=0.05)
parser.add_argument("--psa_add_hs", action=arg.BooleanOptionalAction, default=True)
parser.add_argument("--psa_include_polar_hs", action=arg.BooleanOptionalAction, default=True)

# QED_SA settings.
parser.add_argument("--sa_transform", type=str, default="linear", choices=["linear", "reverse_sigmoid"])
parser.add_argument("--qed_weight", type=float, default=1.0)
parser.add_argument("--sa_weight", type=float, default=1.0)
parser.add_argument("--sa_allow_proxy", action="store_true")

# Existing MPO fallback settings.
parser.add_argument("--aggregate", type=str, default="official", choices=["official", "geometric", "linear", "tchebycheff"])
parser.add_argument("--use_official_guacamol", action=arg.BooleanOptionalAction, default=True)

args = parser.parse_args()

script_dir = Path(__file__).resolve().parent
args.script_dir_for_paths = str(script_dir)
config_path = Path(args.config)
if not config_path.is_absolute():
    config_path = script_dir / config_path

GP = Update_PARAMS(GP, str(config_path))

# Keep this before any CUDA work. If CUDA_VISIBLE_DEVICES is set externally, respect the external value.
os.environ.setdefault("CUDA_VISIBLE_DEVICES", str(GP.CUDA_VISIBLE_DEVICES))
torch.set_float32_matmul_precision("high")
L.seed_everything(args.seed)

import torch._dynamo
torch._dynamo.config.suppress_errors = True

objective_config = build_objective_config(args)
project_name = args.project_name or f"SOTMOL_RL_{args.objective_name}"
exp_tag = args.exp_tag or f"version_{args.objective_name}_{args.regularization_type}"

base_model_kwargs = dict(
    d_model=GP.D_MODEL,
    atom_tokens=GP.TOKENS,
    n_bond_types=GP.N_BOND_TYPES,
    coord_std=GP.COORDS_STD_DEV,
    scale_ot=GP.SCALE_OT,
    self_cond=True,
    coord_noise_std=0.2,
    formulation="endpoint",
    eval_3D_props=False,
    ot_bond_weight=1,
    # Backward compatible: RL_Lightning uses objective_name if provided;
    # otherwise it falls back to reward_name. Passing reward_name keeps old
    # interfaces functional for simple objectives.
    reward_name=args.objective_name,
    reward_beta=args.reward_beta,
    reward_weight_min=args.reward_weight_min,
    reward_weight_max=args.reward_weight_max,
    anchor_weight=args.anchor_weight,
    anchor_loss_weight=args.anchor_loss_weight,
    use_reference_anchor=not args.disable_reference_anchor,
)

# Only pass new objective kwargs if MolGen_RLModel supports them. If your
# rl_interface.py has not yet been updated to forward objective_config into
# RL_Lightning, reward_name still works for objectives with default configs.
sig = inspect.signature(MolGen_RLModel.__init__)
params = sig.parameters
accepts_var_kwargs = any(p.kind == inspect.Parameter.VAR_KEYWORD for p in params.values())
if accepts_var_kwargs or "objective_name" in params:
    base_model_kwargs["objective_name"] = args.objective_name
if accepts_var_kwargs or "objective_config" in params:
    base_model_kwargs["objective_config"] = objective_config

model = MolGen_RLModel(**base_model_kwargs)

prior_ckpt = script_dir / "prior.ckpt"
datasets_dir = script_dir.parent / "datasets"

base_train_datafile = datasets_dir / "train.smol"
base_val_datafile = datasets_dir / "val.smol"
base_test_datafile = datasets_dir / "test.smol"

filter_requested = args.template_atom_count_splits != "none" and (
    args.template_atom_count_min is not None or args.template_atom_count_max is not None
)

train_datafile = _resolve_datafile_for_split(
    split="train",
    default_path=base_train_datafile,
    args=args,
    should_filter_split=filter_requested and args.template_atom_count_splits in {"train", "all"},
)
val_datafile = _resolve_datafile_for_split(
    split="val",
    default_path=base_val_datafile,
    args=args,
    should_filter_split=filter_requested and args.template_atom_count_splits == "all",
)
test_datafile = _resolve_datafile_for_split(
    split="test",
    default_path=base_test_datafile,
    args=args,
    should_filter_split=filter_requested and args.template_atom_count_splits == "all",
)

print(f"[train_rl] objective_name={args.objective_name}")
print(f"[train_rl] objective_config={objective_config}")
print(f"[train_rl] train_datafile={train_datafile}")
print(f"[train_rl] val_datafile={val_datafile}")
print(f"[train_rl] test_datafile={test_datafile}")
print(f"[train_rl] CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES')}")
print(f"[train_rl] project_name={project_name}, exp_tag={exp_tag}")

model.Train(
    train_datafile=train_datafile,
    val_datafile=val_datafile,
    test_datafile=test_datafile,
    epochs=args.epochs,
    save_path=str(script_dir / "models"),
    project_name=project_name,
    load_ckpt=str(prior_ckpt),
    lr=GP.LR,
    debug=False,
    ngpus=1,
    batchsize=args.batchsize,
    mini_batchsize=args.mini_batchsize,
    max_steps=args.max_steps,
    log_steps=args.log_steps,
    exp_tag=exp_tag,
    regularization_type=args.regularization_type,
)
